Revises test error messages
jmjkim/practice pull request #5
Opened 2023-02-18 21:53 UTC by jmjkim

테스트 에러 메세지 통상적인 룰에 맞게 수정하였습니다.

2023-02-19 03:49 UTC, morishjs requested changes

2023-02-19 03:49 UTC, morishjs commented on test/App.test.tsx
> +        it('#1 min(5) - it should render an error message if input length is less than 5.', () => {
아 이게 보면

it('...')

이렇게 되어있으니까

it ('it should be...')가 아니라 it('should be...') 이런 식으로 하면 됩니다

2023-02-20 02:32 UTC, jmjkim commented on test/App.test.tsx
> +        it('#1 min(5) - it should render an error message if input length is less than 5.', () => {
오케이 다시 수정했어!

2023-02-20 03:13 UTC, morishjs approved these changes

2023-02-20 03:13 UTC, merged